#' Plot starting points of HYSPLIT input data frame
#'
#' The function creates a ggplot object depicting the origin points of the 
#' input data frame.
#'
#' @param run_df HYSPLIT input data frame
#' @param pt_size "size" entry for geom_point()
plot_start_points <- function(run_df,
                              pt_size = 1.5) {
  
  if (all(names(run_df) != 'date')) {
    run_df$date <- run_df$date_i
  }
  ll.distinct <- run_df %>%
    dplyr::mutate(date = as.Date(date),
                  year = year(date),
                  date_i = date) %>%
    dplyr::select(lon, lat, date_i) %>%
    dplyr::distinct()
  g <- ggplot() +
    geom_point(data = ll.distinct,  aes(x = lon, y = lat), size = pt_size) + 
    #facet_wrap(vars(year)) +
    labs(x = 'Longitude', y = 'Latitude') +
    theme_minimal() +
    theme(axis.title.x = element_text(size = 12, 
                                      margin = margin(t = 10)),
          axis.title.y = element_text(size = 12, 
                                      margin = margin(r = 10)))
  return(g)
  
}

#' Plot trajectories from HYSPLIT output
#'
#' The function creates a ggplot object depicting the trajectories generated by 
#' HYSPLIT. By default, the plot is faceted by date.
#'
#' @param traj_df HYSPLIT output data frame
#' @param line_transparency "alpha" entry for geom_line()
#' @param line_width "linewidth" entry for geom_line()
#' @param origin_pt_size "size" entry for geom_point() at origins
#' @param traj_pt_size "size" entry for geom_point() at each hour along 
#'   trajectories
#' @param title plot title
#' @param facet_dates TRUE or FALSE; create facets for unique starting dates 
#'   in the HYSPLIT output
plot_trajectories <- function(traj_df,
                              line_transparency = 1,
                              line_width = 1.25, 
                              origin_pt_size = 2,
                              traj_pt_size = 1.5, 
                              title = NULL,
                              facet_dates = FALSE) {
  
  traj_df <- traj_df %>%
    mutate(date_i = as.Date(date_i))
  start_pts <- subset(traj_df, hour_along == 0)
  g <- plot_start_points(start_pts,
                         pt_size = origin_pt_size)
  
  g.traj <- g + 
    geom_path(data = traj_df, aes(x = lon, y = lat,
                                  group = traj_id_full, col = factor(height_i)),
              alpha = line_transparency, linewidth = line_width) +
    geom_point(data = traj_df, aes(x = lon, y = lat,
                                   col = factor(height_i)), size = traj_pt_size) +
    geom_point(data = start_pts, aes(x = lon, y = lat), size = traj_pt_size) +
    labs(col = 'Starting \nHeight (m)', title = title) +
    theme(legend.title = element_text(hjust = 0.5))
  if (facet_dates) {
    g.traj <- g.traj + facet_wrap(vars(date_i))
  }
  return(g.traj)
}
